= The OpenDevStack documentation

== Why we chose Antora

As we release new versions of OpenDevStack with new or changed functionality and configuration, it should always be clear, which documentation applies to which release.
Thus we follow the philosophy: manage docs as code. Which means:

* Storing content in a version control system alongside with the code.
* Separating content, configuration, and presentation
* Reusing shared materials (Don't repeat yourself)

Antora is a static site generator by the same folks behind the AsciiDoctor project that follows this practices.
The engine converts a collection of version controlled documentation written in AsciiDoc into an html site.
The project, while new, is active and responsive and has already made released v2.0 and is being embraced by static site documentarians, like Fedora, Couchbase, Owncloud, Mule.

== How is the documentation organized?

The documentation is contained in the `doc` subdirectory of every project. Every `doc` directory is the root of an https://docs.antora.org/antora/2.0/component-structure/[Antora Component].
We have additional projects containing the _playbook_ and the UI customization.

* ods-documentation
* ods-docs-ui

We also maintain a third repository `ods-guides` that provide more complete Guides that refer to multiple OpenDevStack components, like the xref:common:getting-started.adoc[*Getting Started*] guide.

.Antora components and relevant repositories
|===
|github-repo | antora component | modules

| ods-core 
| https://github.com/opendevstack/ods-core/tree/master/docs[ods-core]
| infrastructure-setup, jenkins, nexus, ROOT, shared-images, sonarqube

| ods-jenkins-shared-library
| https://github.com/opendevstack/ods-jenkins-shared-library/tree/master/docs[ods-jenkins-shared-library]
| ROOT

| ods-provisioning-app
| https://github.com/opendevstack/ods-provisioning-app/tree/master/docs[ods-provisioning-app]
| ROOT

| opendevstack.github.io
| https://github.com/opendevstack/opendevstack.github.io/tree/master/docs[commons]
| getting-started, ROOT
|===

== How to build the site locally?
A guide for building the documentation localy is provided in the https://github.com/opendevstack/ods-documentation/blob/master/README.adoc[ods-documentation project].


== How to contribute documentation

At least you should 

* Fork the required ods-projects
* Make your changes and push them to your github account
* Issue a Pull Request against the original repository

== How is the documentation built on Github?

The documentation will be build on travis and pushed back to the ods-documentation repository.
The https://github.com/opendevstack/ods-documentation/blob/master/.travis.yml[travis] file is located in the ods-documentation project.

WARNING: This means, if a "documentation" Pull Request is merged, the documentation is not automatically built and deployed. You should add an
entry to the https://github.com/opendevstack/ods-documentation/blob/master/CHANGELOG.adoc[documentation changelog] and issue a PR.
Only when this is merged, the new documentation is generated.











